"""Lesson analyzer context returned to agents.

This is what the lesson analyzer service returns and passes to all other components.
"""

from typing import List, Dict, Optional
from pydantic import BaseModel, Field


class StudentApproach(BaseModel):
    """How a specific student profile would approach this lesson's problem.
    
    Generated by the lesson analyzer for each student profile to inform
    how that student agent should think about the problem.
    """
    
    student_id: str = Field(description="ID of the student profile")
    student_name: str = Field(description="Name of the student profile")
    thinking_approach: str = Field(
        description="How this specific student would naturally approach/think about the problem"
    )


class LessonContext(BaseModel):
    """Extracted lesson context from a lesson plan.
    
    This is what the lesson analyzer returns. It contains:
    - Core lesson info (grade, subject, topic)
    - Learning objectives and key concepts
    - A summary describing how students at this grade think about this topic
    - The actual mathematical problem being discussed
    - Subskills/success criteria for high-quality discourse on this problem
    - Student approaches indexed by student_id (so each student agent knows their approach)
    
    This is passed to:
    - Student agents (with their specific approach included)
    - Feedback agents (so they can evaluate against subskills)
    - Lesson summary agents (context for overall feedback)
    """
    
    grade_level: str = Field(description="Grade level (e.g., '3rd grade', '11th grade', 'K-2')")
    subject: str = Field(description="Subject area (e.g., 'Mathematics', 'Algebra')")
    topic: str = Field(description="Specific topic (e.g., 'Linear Equations', 'Fractions')")
    learning_objectives: List[str] = Field(description="What students should learn")
    key_concepts: List[str] = Field(description="Important concepts/vocabulary")
    context_summary: str = Field(
        description="Summary of how students at this grade level typically approach this topic"
    )
    
    # The actual mathematical problem being discussed
    mathematical_problem: Optional[str] = Field(
        default=None,
        description="The specific mathematical problem or scenario (e.g., the fish/tanks problem)"
    )
    
    # Subskills/success criteria for this specific problem
    # What a teacher should look for when facilitating discussion
    subskills: List[str] = Field(
        default_factory=list,
        description="Key subskills/success criteria that indicate high-quality mathematical discourse on this problem"
    )
    
    # Student approaches indexed by ID
    # Each student agent will use their own approach from this dict
    student_approaches: Dict[str, StudentApproach] = Field(
        default_factory=dict,
        description="Map of student_id -> StudentApproach, generated for each profile to inform how they think about this problem"
    )
