"""Lesson analyzer LLM output schema.

What Gemini returns when analyzing a lesson plan.
"""

from pydantic import BaseModel, Field
from typing import List


class StudentApproachOutput(BaseModel):
    """How a specific student would approach the lesson's problem."""
    
    student_id: str = Field(description="ID of the student profile")
    student_name: str = Field(description="Name of the student")
    learning_style: str = Field(description="The student's learning style")
    thinking_approach: str = Field(description="How this student would think about the problem")


class LessonAnalysisOutput(BaseModel):
    """Output schema for lesson plan analysis - generated by Gemini in one call.
    
    Includes core lesson info plus approaches for each student profile.
    This is the raw output from Gemini with student_approaches as a List.
    """
    
    grade_level: str = Field(description="Grade level (e.g., '3rd grade', '9th grade', 'High School')")
    subject: str = Field(description="Subject area (e.g., 'Mathematics', 'Algebra II')")
    topic: str = Field(description="Specific topic being taught")
    learning_objectives: List[str] = Field(description="What students should learn")
    key_concepts: List[str] = Field(description="Key vocabulary and concepts")
    context_summary: str = Field(description="Brief paragraph on how students at this grade level approach this topic")
    mathematical_problem: str | None = Field(
        default=None,
        description="The specific mathematical problem or scenario"
    )
    student_approaches: List[StudentApproachOutput] = Field(
        description="How each student profile would approach this problem (as List from Gemini)"
    )
